order_of_the_sith/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', include('recruiting_service.urls'), name = 'recruiting_service'),
    path('test/', include('test_service.urls'), name = 'test_service'),
]

recruiting_service/urls.py
from django.urls import path
from . import views

app_name = 'recruiting_service'
urlpatterns = [
    path('', views.Main.as_view(), name='recruiting_service_main'),
    path('sith_list/', views.SithList.as_view(),
         name='recruiting_service_sith_list'),
    path('recruit_create/', views.RecruitCreate.as_view(),
         name='recruiting_service_recruit_create'),
    path('recruit_list/<int:sith_id>/',
         views.RecruitList.as_view(), name='recruit_list'),
    path('recruit_enrollment/<int:sith_id>/<int:recruit_id>/',
         views.RecruitEnrollment.as_view(), name='recruit_enrollment'),
]

test_service/urls.py
from django.urls import path
from . import views

app_name='test_service'
urlpatterns = [
    path('test_list/<int:recruit_id>/', views.TestList.as_view(), name='test_list'),
    path('question_list/<int:recruit_id>/<int:test_id>/', views.QuestionList.as_view(), name = 'question_list'),
]
#

recruiting_service/models.py
from django.db import models


class Planet(models.Model):
    """Планета"""
    name = models.CharField(max_length=255, verbose_name='Наименование')

    class Meta:
        verbose_name = 'Планета'
        verbose_name_plural = 'Планеты'

    def __str__(self):
        return self.name


class Sith(models.Model):
    """Ситх"""
    name = models.CharField(max_length=255, verbose_name='Имя')
    planet = models.ForeignKey(
        to='Planet', verbose_name='Планета обучения', on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Ситх'
        verbose_name_plural = 'Ситхи'

    def __str__(self):
        return 'Имя: {name}, Планета: {planet}.'.format(name=self.name, planet=self.planet)


class Recruit(models.Model):
    """Рекрут"""
    name = models.CharField(max_length=255, verbose_name='Имя')
    planet = models.ForeignKey(
        to='Planet', verbose_name='Планета обитания', on_delete=models.PROTECT)
    age = models.IntegerField(verbose_name='Возрас')
    email = models.EmailField(verbose_name='Email')

    class Meta:
        verbose_name = 'Рекрут'
        verbose_name_plural = 'Рекруты'

    def __str__(self):
        return 'Имя: {name}, Планета: {planet}, Возраст: {age}, Email: {email}'.format(name=self.name, planet=self.planet, age=self.age, email=self.email)


class ShadowHand(models.Model):
    """Рекруты зачисленные ситхом Рукой Тени"""
    recruit = models.ForeignKey(to='Recruit', verbose_name='Рекрут', on_delete=models.PROTECT)
    sith = models.ForeignKey(to='Sith', verbose_name='Ситх', on_delete = models.PROTECT)

    class Meta:
        verbose_name = 'Рука Тени'
        verbose_name_plural = 'Руки Тени'

    def __str__(self):
        return 'Рекрут: {recruit}, Ситх: {sith}'.format(recruit=self.recruit, sith=self.sith)

recruiting_service/views.py
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from . import models
from . import services
from test_service import services as test_services


class Main(generic.TemplateView):
    template_name = 'main/main.html'

    def get_context_data(self, **kwargs):
        context = services.get_sith_shadow_hands_count()
        return context


class SithList(generic.ListView):
    model = models.Sith
    template_name = 'sith/sith_list.html'

    context_object_name = 'siths'


class RecruitCreate(generic.CreateView):
    model = models.Recruit
    template_name = 'recruit/recruit_create.html'

    fields = [
        'name',
        'planet',
        'age',
        'email',
    ]

    def get_success_url(self):
        return reverse('test_service:test_list', args=(self.object.id,))


class RecruitList(generic.TemplateView):
    template_name = 'recruit/recruit_list.html'

    def get_context_data(self, **kwargs):
        context = services.get_recruit_list_for_enrollment()
        context['sith_id'] = self.kwargs.get('sith_id')
        return context


class RecruitEnrollment(generic.TemplateView):
    template_name = 'recruit/recruit_enrollment.html'

    def get_context_data(self, **kwargs):
        context = test_services.get_recruit_answers(self.kwargs.get('recruit_id'))
        return context
        
    def post(self, request, *args, **kwargs):
        recruit = self.kwargs.get('recruit_id')
        sith = self.kwargs.get('sith_id')
        result = services.recruit_enrollment(recruit, sith)
        if result[1] == True: # Проверка на зачисление, если рекрут, с таким id уже был зачислен функция вернет этот объект и False
            messages.info(request, 'Рекрут успешно зачислен')
        else:
            messages.info(request, 'Ошибка')
        return HttpResponseRedirect('/')

recruiting_service/templates/recruit/recruit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type='submit' class="btn btn-success">Далее</button>
</form>
{% endblock %}

recruiting_service/templates/recruit/recruit_answer.html
{% extends 'base.html' %}

{% block content %}

<h3>Выберите рекрута</h3>
<div class="list-group mt-4 mb-4">
    {% for answer in answers %}
    <li>Тест: {{answer.test}}. Вопрос: {{answer.question}}. Ответ: {{answer.variant}}</li>
    {% endfor %}

</div>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Зачислить</button>
</form>
{% endblock %}

recruiting_service/templates/recruit/recruit_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type='submit' class="btn btn-success">Далее</button>
</form>
{% endblock %}

recruiting_service/templates/recruit/recruit_enrollment.html
{% extends 'base.html' %}

{% block content %}

<h3>Ответы рекрута на тест</h3>
<div class="list-group mt-4 mb-4">
    {% for answer in recruit_answers %}
    <li>Тест: {{answer.test}}. Вопрос: {{answer.question}}. Ответ: {{answer.variant}}</li>
    {% endfor %}

</div>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Зачислить</button>
</form>
{% endblock %}

recruiting_service/templates/recruit/recruit_list.html
{% extends 'base.html' %}

{% block content %}

<h3>Выберите рекрута</h3>
<div class="list-group mt-4">
    {% for recruit in recruits %}
    <a href="{% url 'recruiting_service:recruit_enrollment' sith_id recruit.id %}" class="list-group-item list-group-item-action">{{recruit}}</a>

    {% endfor %}
</div>
{% endblock %}